<?php

/**
 * @file
 * Module file.
 */

include_once 'includes/integration_consumer.entity.inc';
include_once 'includes/integration_consumer.hooks.inc';

use Drupal\integration_consumer\Configuration\ConsumerConfiguration;

/**
 * Implements hook_permission().
 */
function integration_consumer_permission() {
  return [
    'administer consumers' => [
      'title' => t('Administer consumers'),
    ],
  ];
}

/**
 * Load consumer entity given its machine name.
 *
 * @param string $machine_name
 *    Consumer configuration entity machine name.
 *
 * @return ConsumerConfiguration
 *    Consumer configuration entity.
 */
function integration_consumer_load_consumer($machine_name) {
  return entity_load_single('integration_consumer', $machine_name);
}

/**
 * Determines whether the given user can perform actions on an entity.
 *
 * @param string $op
 *   Operation being performed: 'view', 'update', 'create' or 'delete'.
 * @param ConsumerConfiguration|NULL $consumer
 *   Optionally an entity to check access for.
 * @param object|NULL $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @param string|NULL $entity_type
 *   The entity type of the entity to check for.
 *
 * @return bool
 *   Whether access is allowed or not.
 *
 * @see entity_type_supports()
 * @see integration_consumer_entity_info()
 */
function integration_consumer_access($op, $consumer, $account, $entity_type) {
  return user_access('administer consumers');
}
