<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_entity_info_alter().
 */
function integration_producer_ui_entity_info_alter(&$info) {
  $info['integration_producer']['admin ui'] = array(
    'controller class' => 'Drupal\integration_ui\Configuration\EntityUiController',
    'path' => 'admin/config/integration/producer',
  );
  return $info;
}

/**
 * Implements hook_integration_ui_form_controllers().
 */
function integration_producer_ui_integration_ui_form_controllers() {
  return array(
    'producer' => 'Drupal\integration_producer_ui\FormControllers\ProducerFormController',
  );
}

/**
 * Implements hook_menu().
 */
function integration_producer_ui_menu() {

  $items['admin/config/integration/producer/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('integration_producer_ui_site_settings'),
    'access arguments' => array('administer producers'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Form builder: Site-wide backend settings.
 *
 * @see integration_producer_ui_menu()
 */
function integration_producer_ui_site_settings() {
  $form['site_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Site settings'),
  );
  $form['site_settings']['integration_producer_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Producer ID'),
    '#default_value' => variable_get('integration_producer_id', ''),
    '#description' => t("Global producer ID for this site, set on all produced documents."),
    '#required' => TRUE,
  );
  return system_settings_form($form);
}
