<?php

/**
 * @file
 * Module file.
 */

include_once 'includes/integration_producer.entity.inc';
include_once 'includes/integration_producer.hooks.inc';

use Drupal\integration_producer\Configuration\ProducerConfiguration;

/**
 * Implements hook_permission().
 */
function integration_producer_permission() {
  return [
    'administer producers' => [
      'title' => t('Administer producers'),
    ],
  ];
}

/**
 * Load producer entity given its machine name.
 *
 * @param string $machine_name
 *    Producer configuration entity machine name.
 *
 * @return ProducerConfiguration
 *    Producer configuration entity.
 */
function integration_producer_load_producer($machine_name) {
  return entity_load_single('integration_producer', $machine_name);
}

/**
 * Determines whether the given user can perform actions on an entity.
 *
 * @param string $op
 *   Operation being performed: 'view', 'update', 'create' or 'delete'.
 * @param ProducerConfiguration|NULL $producer
 *   Optionally an entity to check access for.
 * @param object|NULL $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @param string|NULL $entity_type
 *   The entity type of the entity to check for.
 *
 * @return bool
 *   Whether access is allowed or not.
 *
 * @see entity_type_supports()
 * @see integration_producer_entity_info()
 */
function integration_producer_access($op, $producer, $account, $entity_type) {
  return user_access('administer producers');
}
