<?php
/**
 * @file
 * Code for the Integration Test feature.
 */

include_once 'integration_test.features.inc';

/**
 * Implements hook_migrate_api().
 */
function integration_test_migrate_api() {
  return array(
    'api' => 2,
    'groups' => array(
      'IntegrationTest' => array(
        'title' => t('Integration Test'),
      ),
    ),
    'migrations' => array(
      'IntegrationTestArticles' => array(
        'class_name' => 'IntegrationTestArticlesMigration',
        'group_name' => 'IntegrationTest',
      ),
      'IntegrationTestNews' => array(
        'class_name' => 'IntegrationTestNewsMigration',
        'group_name' => 'IntegrationTest',
      ),
      'IntegrationTestCategories' => array(
        'class_name' => 'IntegrationTestCategoriesMigration',
        'group_name' => 'IntegrationTest',
      ),
    ),
  );
}
