<?php
/**
 * @file
 * Code for the Integration Test feature.
 */

include_once 'integration_test.features.inc';

/**
 * Implements hook_install().
 */
function integration_test_install() {
  // Force registration of migration classes.
  migrate_static_registration();
  // Make sure all sensitive configuration is correctly applied.
  features_revert(['integration_test' => ['taxonomy', 'variable']]);
}
