<?php
/**
 * @file
 * Code for the Integration Test feature.
 */

include_once 'integration_test.features.inc';

/**
 * Implements hook_migrate_api().
 */
function integration_test_migrate_api() {
  return [
    'api' => 2,
    'groups' => [
      'IntegrationTest' => [
        'title' => t('Integration Test'),
      ],
    ],
    'migrations' => [
      'IntegrationTestArticles' => [
        'class_name' => 'IntegrationTestArticlesMigration',
        'group_name' => 'IntegrationTest',
      ],
      'IntegrationTestNews' => [
        'class_name' => 'IntegrationTestNewsMigration',
        'group_name' => 'IntegrationTest',
      ],
      'IntegrationTestCategories' => [
        'class_name' => 'IntegrationTestCategoriesMigration',
        'group_name' => 'IntegrationTest',
      ],
    ],
  ];
}
