<?php

/**
 * @file
 * Module file.
 */

include_once 'includes/integration.entity.inc';
include_once 'includes/integration.hooks.inc';

use Drupal\integration\Backend\Configuration\BackendConfiguration;

/**
 * Implements hook_permission().
 */
function integration_permission() {
  return [
    'administer backends' => [
      'title' => t('Administer integration layer backends'),
    ],
  ];
}

/**
 * Determines whether the given user can perform actions on an entity.
 *
 * @param string $op
 *   Operation being performed: 'view', 'update', 'create' or 'delete'.
 * @param BackendConfiguration|NULL $backend
 *   Optionally an entity to check access for.
 * @param object|NULL $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @param string|NULL $entity_type
 *   The entity type of the entity to check for.
 *
 * @return bool
 *   Whether access is allowed or not.
 *
 * @see entity_type_supports()
 * @see integration_producer_entity_info()
 */
function integration_backend_access($op, $backend, $account, $entity_type) {
  return user_access('administer backends');
}

/**
 * Load backend entity given its machine name.
 *
 * @param string $machine_name
 *    Backend configuration entity machine name.
 *
 * @return BackendConfiguration
 *    Backend configuration entity.
 */
function integration_load_backend($machine_name) {
  return entity_load_single('integration_backend', $machine_name);
}
