<?php

/**
 * @file
 * Module file.
 */

/**
 * Implements hook_entity_info_alter().
 */
function integration_consumer_ui_entity_info_alter(&$info) {
  $info['integration_consumer']['admin ui'] = [
    'controller class' => 'Drupal\integration_ui\Configuration\EntityUiController',
    'path' => 'admin/config/integration/consumer',
  ];
  return $info;
}

/**
 * Implements hook_integration_ui_form_controllers().
 */
function integration_consumer_ui_integration_ui_form_controllers() {
  return [
    'consumer' => 'Drupal\integration_consumer_ui\FormControllers\ConsumerFormController',
  ];
}
